server {
    listen 8000;
<<<<<<< .merge_file_F9gDFU
    server_name healthcare_app.local;
=======
    server_name ptvx.local;
>>>>>>> .merge_file_k76oRI
    root /var/www/html;

    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ /\.ht {
        deny all;
    }
}
